# Generated by Django 3.2.2 on 2021-05-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_joined_for_format',), 'verbose_name_plural': 'Products'},
        ),
    ]
