# Generated by Django 3.2.2 on 2021-05-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210510_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='date_joined_for_format',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_login',
            new_name='last_login_for_format',
        ),
    ]
